# Generated by Django 6.0 on 2025-12-20 04:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriaClinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_evaluacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('diagnostico', models.TextField()),
                ('pronostico', models.TextField(blank=True, null=True)),
                ('tratamiento_planificado', models.TextField()),
                ('notas_arcos_movimiento', models.TextField(blank=True, null=True)),
                ('escala_eva', models.CharField(blank=True, choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], help_text='Escala de Dolor EVA (0-10)', max_length=2, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historias_clinicas', to='pacientes.paciente')),
            ],
            options={
                'verbose_name': 'Historia Clínica',
                'verbose_name_plural': 'Historias Clínicas',
                'ordering': ['-fecha_evaluacion'],
            },
        ),
        migrations.CreateModel(
            name='GraficoEvolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('numero_sesion', models.PositiveIntegerField()),
                ('escala_eva', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('arcos_movimiento_grados', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('fuerza_muscular', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('historia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graficos_evolucion', to='historiaclinica.historiaclinica')),
            ],
            options={
                'verbose_name': 'Gráfico de Evolución',
                'verbose_name_plural': 'Gráficos de Evolución',
                'ordering': ['fecha'],
            },
        ),
        migrations.CreateModel(
            name='EscalaDaniels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('musculo', models.CharField(max_length=200)),
                ('grado', models.CharField(choices=[('0', '0 - Parálisis'), ('1', '1 - Contracción visible/palpable sin movimiento'), ('2', '2 - Movimiento con eliminación de gravedad'), ('3', '3 - Movimiento contra gravedad'), ('4', '4 - Movimiento contra resistencia moderada'), ('5', '5 - Fuerza normal')], max_length=1)),
                ('notas', models.TextField(blank=True, null=True)),
                ('historia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escala_daniels', to='historiaclinica.historiaclinica')),
            ],
            options={
                'verbose_name': 'Escala de Daniels',
                'verbose_name_plural': 'Escala de Daniels',
            },
        ),
        migrations.CreateModel(
            name='EjercioTerapeutico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_ejercicio', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('series', models.PositiveIntegerField(default=3)),
                ('repeticiones', models.CharField(max_length=50)),
                ('duracion_segundos', models.PositiveIntegerField(blank=True, null=True)),
                ('frecuencia', models.CharField(max_length=100)),
                ('es_ejercicio_casa', models.BooleanField(default=True)),
                ('dias_semana', models.CharField(blank=True, max_length=100, null=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('fecha_prescripcion', models.DateField(auto_now_add=True)),
                ('historia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejercicios_terapeuticos', to='historiaclinica.historiaclinica')),
            ],
            options={
                'verbose_name': 'Ejercicio Terapéutico',
                'verbose_name_plural': 'Ejercicios Terapéuticos',
            },
        ),
        migrations.CreateModel(
            name='ArcosMovimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articulation', models.CharField(max_length=100)),
                ('flexion', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('extension', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('abduccion', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('adduccion', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('rotacion_interna', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('rotacion_externa', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('historia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arcos_movimiento', to='historiaclinica.historiaclinica')),
            ],
            options={
                'verbose_name': 'Arco de Movimiento',
                'verbose_name_plural': 'Arcos de Movimiento',
            },
        ),
        migrations.CreateModel(
            name='PruebaFuncional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_prueba', models.CharField(max_length=200)),
                ('resultado', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('historia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pruebas_funcionales', to='historiaclinica.historiaclinica')),
            ],
            options={
                'verbose_name': 'Prueba Funcional',
                'verbose_name_plural': 'Pruebas Funcionales',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='EvolucionTratamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_sesion', models.DateField()),
                ('numero_sesion', models.PositiveIntegerField()),
                ('escala_eva_sesion', models.CharField(blank=True, choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], help_text='EVA al inicio de la sesión', max_length=2, null=True)),
                ('notas_sesion', models.TextField()),
                ('progreso', models.TextField(blank=True, null=True)),
                ('cambios_detectados', models.TextField(blank=True, null=True)),
                ('notas_arcos_actual', models.TextField(blank=True, null=True)),
                ('recomendaciones', models.TextField(blank=True, null=True)),
                ('historia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evoluciones', to='historiaclinica.historiaclinica')),
            ],
            options={
                'verbose_name': 'Evolución de Tratamiento',
                'verbose_name_plural': 'Evoluciones de Tratamiento',
                'ordering': ['-fecha_sesion'],
                'unique_together': {('historia', 'numero_sesion')},
            },
        ),
    ]
