# Generated by Django 6.0 on 2025-12-20 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historiaclinica', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstudioClinico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('radiografia', 'Radiografía'), ('resonancia', 'Resonancia'), ('tomografia', 'Tomografía'), ('ecografia', 'Ecografía'), ('analisis_sanguineos', 'Análisis sanguíneos'), ('examen_orina', 'Examen general de orina'), ('perfil_hormonal', 'Perfil hormonal'), ('otros', 'Otros')], max_length=50)),
                ('fecha_estudio', models.DateField()),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('resultado', models.TextField(blank=True, null=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='estudios/')),
                ('historia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudios_clinicos', to='historiaclinica.historiaclinica')),
            ],
            options={
                'verbose_name': 'Estudio clínico',
                'verbose_name_plural': 'Estudios clínicos',
                'ordering': ['-fecha_estudio'],
            },
        ),
    ]
