# Generated by Django 6.0 on 2025-12-20 04:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('edad', models.PositiveIntegerField()),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1)),
                ('telefono', models.CharField(max_length=20)),
                ('telefono_emergencia', models.CharField(blank=True, max_length=20, null=True)),
                ('domicilio', models.TextField()),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('alergias', models.TextField(blank=True, null=True)),
                ('grupo_sanguineo', models.CharField(blank=True, choices=[('O+', 'O+'), ('O-', 'O-'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=3, null=True)),
                ('rh', models.CharField(blank=True, choices=[('+', 'Positivo'), ('-', 'Negativo')], max_length=1, null=True)),
                ('religion', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_paciente', models.CharField(choices=[('consulta_unica', 'Consulta Única (Masajes Relajantes)'), ('patologia', 'Patologías (Tratamiento Completo)'), ('estetico', 'Masajes Reductivos (Tratamientos Estéticos)')], max_length=20)),
                ('es_frecuente', models.BooleanField(default=False)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='EstudiosClinico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('radiografias', models.FileField(blank=True, null=True, upload_to='estudios/radiografias/')),
                ('resonancias', models.FileField(blank=True, null=True, upload_to='estudios/resonancias/')),
                ('tomografia', models.FileField(blank=True, null=True, upload_to='estudios/tomografia/')),
                ('ecografia', models.FileField(blank=True, null=True, upload_to='estudios/ecografia/')),
                ('otros_estudios', models.FileField(blank=True, null=True, upload_to='estudios/otros/')),
                ('descripcion_otros', models.TextField(blank=True, null=True)),
                ('analisis_sanguineos', models.FileField(blank=True, null=True, upload_to='estudios/analisis_sanguineos/')),
                ('examen_general_orina', models.FileField(blank=True, null=True, upload_to='estudios/examen_orina/')),
                ('perfil_hormonal', models.FileField(blank=True, null=True, upload_to='estudios/perfil_hormonal/')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='estudios_clinicos', to='pacientes.paciente')),
            ],
            options={
                'verbose_name': 'Estudio Clínico',
                'verbose_name_plural': 'Estudios Clínicos',
            },
        ),
        migrations.CreateModel(
            name='DatosNutricion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carnes', models.TextField(blank=True, help_text='Tipos de carnes consumidas', null=True)),
                ('legumbres', models.TextField(blank=True, help_text='Legumbres consumidas', null=True)),
                ('hidratos_carbono', models.TextField(blank=True, null=True)),
                ('lipidos', models.TextField(blank=True, null=True)),
                ('proteinas_cantidad', models.CharField(blank=True, max_length=100, null=True)),
                ('hidratacion', models.TextField(blank=True, null=True)),
                ('suplementacion', models.TextField(blank=True, null=True)),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='datos_nutricion', to='pacientes.paciente')),
            ],
            options={
                'verbose_name': 'Datos de Nutrición',
                'verbose_name_plural': 'Datos de Nutrición',
            },
        ),
        migrations.CreateModel(
            name='AntecedentesNoPatologicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realiza_actividad_fisica', models.BooleanField(default=False)),
                ('frecuencia_ejercicio', models.CharField(blank=True, choices=[('no', 'No realiza'), ('ocasional', 'Ocasional'), ('regular', '3-4 veces por semana'), ('intenso', 'Diario o casi diario')], max_length=20, null=True)),
                ('tipo_ejercicio', models.TextField(blank=True, null=True)),
                ('tipo_alimentacion', models.CharField(blank=True, choices=[('omnivora', 'Omnívora'), ('vegetariana', 'Vegetariana'), ('vegana', 'Vegana'), ('cetogenica', 'Cetogénica'), ('mediterranea', 'Mediterránea'), ('otra', 'Otra')], max_length=20, null=True)),
                ('descripcion_alimentacion', models.TextField(blank=True, null=True)),
                ('horas_sueno', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(24)])),
                ('calidad_sueno', models.CharField(blank=True, max_length=50, null=True)),
                ('litros_agua_diarios', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('usa_suplementos', models.BooleanField(default=False)),
                ('suplementos_descripcion', models.TextField(blank=True, null=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='antecedentes_no_patologicos', to='pacientes.paciente')),
            ],
            options={
                'verbose_name': 'Antecedentes No Patológicos',
                'verbose_name_plural': 'Antecedentes No Patológicos',
            },
        ),
        migrations.CreateModel(
            name='AntecedentePatologicoFemenino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ultima_menstruacion', models.DateField(blank=True, null=True)),
                ('probabilidad_embarazo', models.BooleanField(default=False)),
                ('numero_partos', models.PositiveIntegerField(default=0)),
                ('en_menopausia', models.BooleanField(default=False)),
                ('edad_menopausia', models.PositiveIntegerField(blank=True, null=True)),
                ('paciente', models.OneToOneField(limit_choices_to={'genero': 'F'}, on_delete=django.db.models.deletion.CASCADE, related_name='antecedentes_femeninos', to='pacientes.paciente')),
            ],
            options={
                'verbose_name': 'Antecedente Femenino',
                'verbose_name_plural': 'Antecedentes Femeninos',
            },
        ),
        migrations.CreateModel(
            name='AntecedentePatologico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_antecedente', models.CharField(choices=[('personal', 'Personal'), ('familiar', 'Familiar de Primer Grado')], max_length=20)),
                ('patologia', models.CharField(choices=[('hipertension', 'Hipertensión'), ('diabetes', 'Diabetes'), ('cancer', 'Cáncer'), ('trigliceridos', 'Triglicéridos Altos'), ('obesidad', 'Obesidad'), ('tiroides', 'Tiroides'), ('sop', 'SOP (Síndrome Ovario Poliquístico)'), ('menopausia', 'Menopausia'), ('otro', 'Otro')], max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('año_diagnostico', models.PositiveIntegerField(blank=True, null=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='antecedentes_patologicos', to='pacientes.paciente')),
            ],
            options={
                'verbose_name': 'Antecedente Patológico',
                'verbose_name_plural': 'Antecedentes Patológicos',
            },
        ),
        migrations.CreateModel(
            name='AntecedenteCirugias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_cirugia', models.CharField(max_length=200)),
                ('fecha', models.DateField()),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cirugia', to='pacientes.paciente')),
            ],
            options={
                'verbose_name': 'Cirugía',
                'verbose_name_plural': 'Cirugías',
            },
        ),
    ]
