# Generated by Django 6.0 on 2025-12-29 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='antecedentepatologicofemenino',
            name='paciente',
        ),
        migrations.RenameField(
            model_name='antecedentepatologico',
            old_name='descripcion',
            new_name='notas',
        ),
        migrations.RenameField(
            model_name='antecedentesnopatologicos',
            old_name='descripcion_alimentacion',
            new_name='diagnostico',
        ),
        migrations.RenameField(
            model_name='antecedentesnopatologicos',
            old_name='suplementos_descripcion',
            new_name='dieta',
        ),
        migrations.RemoveField(
            model_name='antecedentepatologico',
            name='año_diagnostico',
        ),
        migrations.RemoveField(
            model_name='antecedentepatologico',
            name='patologia',
        ),
        migrations.RemoveField(
            model_name='antecedentepatologico',
            name='tipo_antecedente',
        ),
        migrations.RemoveField(
            model_name='antecedentesnopatologicos',
            name='usa_suplementos',
        ),
        migrations.AddField(
            model_name='antecedentepatologico',
            name='cancer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='antecedentepatologico',
            name='cirugias',
            field=models.TextField(blank=True, help_text='Descripción de cirugías realizadas', null=True),
        ),
        migrations.AddField(
            model_name='antecedentepatologico',
            name='diabetes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='antecedentepatologico',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='antecedentepatologico',
            name='fecha_ultima_menstruacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='antecedentepatologico',
            name='hipertension',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='antecedentepatologico',
            name='menopausia',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='antecedentepatologico',
            name='numero_partos',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='antecedentepatologico',
            name='obesidad',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='antecedentepatologico',
            name='probabilidad_embarazo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='antecedentepatologico',
            name='sop',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='antecedentepatologico',
            name='tiroides',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='antecedentepatologico',
            name='trigliceridos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='antecedentesnopatologicos',
            name='carnes',
            field=models.TextField(blank=True, help_text='Tipos de carnes consumidas', null=True),
        ),
        migrations.AddField(
            model_name='antecedentesnopatologicos',
            name='hidratacion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='antecedentesnopatologicos',
            name='hidratos_carbono',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='antecedentesnopatologicos',
            name='legumbres',
            field=models.TextField(blank=True, help_text='Legumbres consumidas', null=True),
        ),
        migrations.AddField(
            model_name='antecedentesnopatologicos',
            name='lipidos',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='antecedentesnopatologicos',
            name='notas_dieta',
            field=models.TextField(blank=True, help_text='Notas adicionales sobre la dieta', null=True),
        ),
        migrations.AddField(
            model_name='antecedentesnopatologicos',
            name='pronostico',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='antecedentesnopatologicos',
            name='proteinas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='antecedentesnopatologicos',
            name='regimen_alimenticio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='antecedentesnopatologicos',
            name='suplementacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='antecedentepatologico',
            name='paciente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='antecedentes_patologicos', to='pacientes.paciente'),
        ),
        migrations.DeleteModel(
            name='AntecedenteCirugias',
        ),
        migrations.DeleteModel(
            name='AntecedentePatologicoFemenino',
        ),
    ]
