# Generated by Django 6.0 on 2025-12-30 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0003_alter_paciente_fecha_nacimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='email',
        ),
    ]
