# Generated by Django 6.0 on 2025-12-20 04:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('historiaclinica', '0001_initial'),
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TecnicaTratamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('es_radiofrecuencia', models.BooleanField(default=False)),
                ('es_facial', models.BooleanField(default=False)),
                ('es_masaje', models.BooleanField(default=False)),
                ('es_crio', models.BooleanField(default=False)),
                ('es_cavitacion', models.BooleanField(default=False)),
                ('otra_tipo', models.CharField(blank=True, max_length=200, null=True)),
                ('duracion_minutos_tipica', models.PositiveIntegerField(default=60)),
                ('zonas_indicadas', models.TextField(help_text='Zonas del cuerpo donde se aplica típicamente')),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Técnica de Tratamiento',
                'verbose_name_plural': 'Técnicas de Tratamiento',
            },
        ),
        migrations.CreateModel(
            name='TratamientoEstetico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(auto_now_add=True)),
                ('fecha_fin_planificada', models.DateField(blank=True, null=True)),
                ('objetivo_principal', models.TextField()),
                ('zona_trabajo', models.TextField()),
                ('tecnicas_descripcion', models.TextField(blank=True, null=True)),
                ('es_tratamiento_facial', models.BooleanField(default=False)),
                ('usa_radiofrecuencia', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('historia_clinica', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tratamiento_estetico', to='historiaclinica.historiaclinica')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tratamientos_esteticos', to='pacientes.paciente')),
            ],
            options={
                'verbose_name': 'Tratamiento Estético',
                'verbose_name_plural': 'Tratamientos Estéticos',
            },
        ),
        migrations.CreateModel(
            name='TratamientoFacial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_piel', models.CharField(blank=True, choices=[('normal', 'Normal'), ('seca', 'Seca'), ('grasa', 'Grasa'), ('mixta', 'Mixta'), ('sensible', 'Sensible')], max_length=20, null=True)),
                ('problemas_piel', models.TextField(blank=True, null=True)),
                ('usa_radiofrecuencia_facial', models.BooleanField(default=False)),
                ('usa_microdermoabracion', models.BooleanField(default=False)),
                ('usa_peelings', models.BooleanField(default=False)),
                ('objetivo_facial', models.TextField()),
                ('tratamiento_estetico', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tratamiento_facial', to='tratamientos.tratamientoestetico')),
            ],
            options={
                'verbose_name': 'Tratamiento Facial',
                'verbose_name_plural': 'Tratamientos Faciales',
            },
        ),
        migrations.CreateModel(
            name='ZonaCorporal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zona', models.CharField(choices=[('abdomen_alto', 'Abdomen Alto'), ('cintura', 'Cintura'), ('abdomen_bajo', 'Abdomen Bajo'), ('espalda_alta', 'Espalda Alta'), ('zona_axilar', 'Zona Axilar'), ('espalda_baja', 'Espalda Baja'), ('piernas', 'Piernas'), ('femur_proximal', 'Parte Proximal de Fémur'), ('femur_medial', 'Parte Medial Fémur'), ('cadera_distal', 'Parte Distal de Cadera'), ('cara', 'Cara/Facial'), ('cuello', 'Cuello'), ('brazos', 'Brazos'), ('glúteos', 'Glúteos'), ('otra', 'Otra Zona')], max_length=30)),
                ('descripcion_adicional', models.CharField(blank=True, max_length=200, null=True)),
                ('tratamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zonas_corporales', to='tratamientos.tratamientoestetico')),
            ],
            options={
                'verbose_name': 'Zona Corporal',
                'verbose_name_plural': 'Zonas Corporales',
                'unique_together': {('tratamiento', 'zona')},
            },
        ),
        migrations.CreateModel(
            name='EvolucionTratamientoEstetico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_sesion', models.PositiveIntegerField()),
                ('fecha_sesion', models.DateField()),
                ('cambios_visibles', models.TextField(blank=True, null=True)),
                ('satisfaccion_paciente', models.CharField(blank=True, choices=[('muy_satisfecho', 'Muy Satisfecho'), ('satisfecho', 'Satisfecho'), ('neutral', 'Neutral'), ('insatisfecho', 'Insatisfecho')], max_length=50, null=True)),
                ('tecnica_utilizada', models.TextField()),
                ('duracion_minutos', models.PositiveIntegerField(default=60)),
                ('notas', models.TextField(blank=True, null=True)),
                ('recomendaciones', models.TextField(blank=True, null=True)),
                ('tratamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evoluciones', to='tratamientos.tratamientoestetico')),
            ],
            options={
                'verbose_name': 'Evolución Tratamiento Estético',
                'verbose_name_plural': 'Evoluciones Tratamiento Estético',
                'ordering': ['numero_sesion'],
                'unique_together': {('tratamiento', 'numero_sesion')},
            },
        ),
        migrations.CreateModel(
            name='MedidasZona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_sesion', models.IntegerField(choices=[(1, 'Sesión 1 (Inicial)'), (3, 'Sesión 3-4'), (6, 'Sesión 6-7')])),
                ('medida_cm', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fecha_medicion', models.DateField()),
                ('notas', models.TextField(blank=True, null=True)),
                ('zona_corporal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medidas', to='tratamientos.zonacorporal')),
            ],
            options={
                'verbose_name': 'Medida de Zona',
                'verbose_name_plural': 'Medidas de Zona',
                'ordering': ['numero_sesion'],
                'unique_together': {('zona_corporal', 'numero_sesion')},
            },
        ),
    ]
