# Generated by Django 6.0 on 2026-01-10 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tratamientos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoCuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costo_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('tratamiento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='estado_cuenta', to='tratamientos.tratamientoestetico')),
            ],
            options={
                'verbose_name': 'Estado de Cuenta',
                'verbose_name_plural': 'Estados de Cuenta',
            },
        ),
        migrations.CreateModel(
            name='Anticipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_pago', models.DateField()),
                ('concepto', models.CharField(blank=True, default='Anticipo', max_length=200)),
                ('notas', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('estado_cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anticipos', to='tratamientos.estadocuenta')),
            ],
            options={
                'verbose_name': 'Anticipo',
                'verbose_name_plural': 'Anticipos',
                'ordering': ['fecha_pago'],
            },
        ),
    ]
