# Generated by Django 6.0 on 2026-01-31 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historiaclinica', '0002_estudioclinico'),
        ('tratamientos', '0002_estadocuenta_anticipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tratamientoestetico',
            name='historia_clinica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tratamientos_esteticos', to='historiaclinica.historiaclinica'),
        ),
    ]
