# Generated by Django 6.0 on 2025-12-20 04:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Terapeuta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=20)),
                ('especialidades', models.TextField()),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Terapeuta',
                'verbose_name_plural': 'Terapeutas',
            },
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField()),
                ('duracion_minutos', models.PositiveIntegerField(default=60)),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('ocupada', 'Ocupada'), ('cancelada', 'Cancelada'), ('completada', 'Completada')], default='disponible', max_length=20)),
                ('tipo_sesion', models.CharField(choices=[('sesion_regular', 'Sesión Regular'), ('sesion_estetica', 'Sesión Estética'), ('seguimiento', 'Seguimiento'), ('evaluacion', 'Evaluación Inicial')], max_length=20)),
                ('motivo_cita', models.TextField(blank=True, null=True)),
                ('notas_adicionales', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='pacientes.paciente')),
                ('terapeuta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='citas.terapeuta')),
            ],
            options={
                'verbose_name': 'Cita',
                'verbose_name_plural': 'Citas',
                'ordering': ['fecha_hora'],
                'unique_together': {('terapeuta', 'fecha_hora')},
            },
        ),
        migrations.CreateModel(
            name='CitasProximas',
            fields=[
            ],
            options={
                'verbose_name': 'Cita Próxima',
                'verbose_name_plural': 'Citas Próximas',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('citas.cita',),
        ),
        migrations.CreateModel(
            name='AgendaDisponibilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')])),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('activo', models.BooleanField(default=True)),
                ('terapeuta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidades', to='citas.terapeuta')),
            ],
            options={
                'verbose_name': 'Disponibilidad de Agenda',
                'verbose_name_plural': 'Disponibilidades de Agenda',
                'unique_together': {('terapeuta', 'dia_semana', 'hora_inicio')},
            },
        ),
    ]
